### ISSUE TITLE
В README.md спорные рекомендации

### ISSUE THREAD

**Issue by Claud** [nginx-boilerplate/nginx-boilerplate#58]
Здравствуйте.

> Make sure you have cgi.fix_pathinfo set to "1" or commented out in php.ini

Спорный совет согласно этой статье http://habrahabr.ru/post/100961/ лучше выставить в 0.

Единственный минус, который это даст - `$_SERVER['PHP_SELF']` не заполняется, по этому если он используется :( (например в dle насколько я помню видел такое), то стоит добавить в начало стартового скрипта:
`$_SERVER['PHP_SELF'] = $_SERVER['SCRIPT_NAME'] . $_SERVER['PATH_INFO'];`
Вот это мне кажется и стоит добавить в примечание.

__UPD:__ Кстати в доке по yii2 http://www.yiiframework.com/doc-2.0/guide-installation.html говорят еще и это:

> When using this configuration, you should set cgi.fix_pathinfo=0 in the php.ini file in order to avoid many unnecessary system stat() calls.

**Comment by Umkus** [comment]
README.md обновлен
