### ISSUE TITLE
Consider tcp_nodelay on;

### ISSUE THREAD

**Issue by paulwalker** [nginx-boilerplate/nginx-boilerplate#67]
https://t37.net/nginx-optimization-understanding-sendfile-tcp_nodelay-and-tcp_nopush.html

**Comment by Umkus** [comment]
Thanks, the article rocks. 
Applied for [static files](https://github.com/nginx-boilerplate/nginx-boilerplate/blob/master/boilerplate/locations/static.conf).

**Comment by zachaysan** [comment]
Hi there! If I'm looking at the file correctly it doesn't appear that it has been set to `on`.  Is there a reason for this?

**Comment by Umkus** [comment]
@zachaysan You're right, looks like there wasn't even any commit for this issue. My bad.
