### ISSUE TITLE
ownCloud не работает с текущим php.conf

### ISSUE THREAD

**Issue by OSDDQD** [nginx-boilerplate/nginx-boilerplate#76]
```
fastcgi_param               SCRIPT_NAME $script_name_final;
if ($path_info_final != '') {
    set $request_uri_final $path_info_final$is_args$args;
}
fastcgi_param               REQUEST_URI         $request_uri_final;

```
Собственно из-за данных настроек ownCloud не работает с данным конфигом.
`set $request_uri_final $path_info_final$is_args$args;`
Не работает множество функции owncloud, так-же не показывает список файлов.
При её комментировании не работает только загрузка файлов, помогает комментирование параметра SCRIPT_NAME.

**Comment by Umkus** [comment]
@OSDDQD
Что именно не работает? Как это можно повторить локально?

**Comment by OSDDQD** [comment]
@Umkus не работает upload файлов.
Для того, чтобы повторить локально, достаточно поставить ownCloud и попробовать загрузить файл.

**Comment by Umkus** [comment]
Я, к сожалению, не знаю что такое ownCloud и поставить локально его не могу. Возможно это проблема в нем, а не в самом конфиге.

**Comment by Umkus** [comment]
После 95ebf20ef39e156563abd74b0924cdfa4704ac3d `php.conf` максимально упростился. Попробуйте еще раз с последней версией.
