### ISSUE TITLE
Nginx is starting, bug don't listen

### ISSUE THREAD

**Issue by vinvin27** [nginx-boilerplate/nginx-boilerplate#77]
Hey Guys,

Im disapointed, your boilerplate looks awesome.
But I can't get it working.

after an failed attempt with all your repository, I tried only with nginx.conf and boilerplate/

nginx is starting
But when I do : netstat -plunt 

No nginx listed :( .. it looks not listen anything :§ 

Im on fresh debian 8 installation.

Thanks for your contribution btw, awesome idea.

**Comment by vinvin27** [comment]
Huum, maybe I found something :

I added 	include /etc/nginx/sites-enabled/*;
instead of 
	include sites-enabled/*;

and working fine :)

**Comment by Umkus** [comment]
`include` expects a file path/mask as an argument. Looks like you are including the path. I don't see how this could work. 

You should be having `sites-enabled/*.conf;` in your `nginx.conf`.

**Comment by vinvin27** [comment]
I mean, with you basic config
I replaced ` sites-enabled/*.conf;` by `/etc/nginx/sites-enabled/*;`
and works now :) 

I assume `*` was replaced on my previous post

**Comment by vinvin27** [comment]
Btw, into Response Header,
I can see :

`Server:nginx` its not normal ? Show be hidden by token off ?

**Comment by Umkus** [comment]
Oh, ok. Maybe you forgot to add the `.conf` extention to your files. Or permission issue.

> its not normal ? Should be hidden by token off ?
What `server_tokens off` does is it hides the version from that header, not removes it. Also from the nginx error pages.

If you're so inclined to affect it, you can only replace it with something else from php.

Something like: 
```php
header('Server: Toster');
```
