### ISSUE TITLE
"Primary script unknown" в логах при попытке открыть несуществующий документ.

### ISSUE THREAD

**Issue by Sferg** [nginx-boilerplate/nginx-boilerplate#78]
Здравствуйте. Установил nginx-boilerplate. При попытке открыть несуществующий документ (release.bmp), вместо ошибки 404 получаю сообщение "File not found" в браузере. В логах ошибок пишется:

`2016/07/26 00:24:57 [error] 27633#27633: *1 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: xxxxx.xxxxxx.com, request: "GET /release.bmp HTTP/1.1", upstream: "fastcgi://unix:/var/run/php7.0-fpm.sock:", host: "xxxxx.xxxxxx.com"`

Комментирую строчки настроек PHP для сайта в /sites-available:

```
#location ~ ^.+\.php(?:/.*)?$
#    {
#        include                 boilerplate/enable/php.conf;
#        fastcgi_pass            xxxxx.xxxxxx.com;
#        limit_req               zone=reqPerSec10 burst=50 nodelay;
#        limit_conn              conPerIp 10;
#    }
```

и снова обращаюсь к несуществующему документу (release.bmp). На сей раз ошибка "500 Internal Server Error", а в логах наблюдаю следующее:

`2016/07/26 00:26:15 [error] 27683#27683: *1 rewrite or internal redirection cycle while internally redirecting to "/index.php/release.bmp", client: xxx.xxx.xxx.xxx, server: xxxxx.xxxxxx.com, request: "GET /release.bmp HTTP/1.1", host: "xxxxx.xxxxxx.com"`

Подскажите, пожалуйста, в чём может быть дело? Существующие документы открываются исправно.

**Comment by fessoga5** [comment]
Похоже они не понимают на русском =)

**Comment by Umkus** [comment]
Скорей проблема в неверном `SCRIPT_FILENAME`. Т.е. тот путь, который устанавливается со стороны nginx не существует на стороне php-fpm.
