### ISSUE TITLE
ALLOW standard request methods

### ISSUE THREAD

**Issue by eikaramba** [nginx-boilerplate/nginx-boilerplate#87]
In file https://github.com/nginx-boilerplate/nginx-boilerplate/blob/master/boilerplate/limits/methods.conf methods PATCH and PUT are not allowed. why? That are standard http requests, used by many restful frameworks. e.g. i'm using feathers.js on nodejs behind nginx. I just added these myself, but would agree to put those by default

**Comment by Umkus** [comment]
One might debate that REST-full services are way less common compared to the bulk of web applications, but for the sake of more generic configuration it makes sense.
