### ISSUE TITLE
Unknown Variable error

### ISSUE THREAD

**Issue by ulic75** [nginx-boilerplate/nginx-boilerplate#89]
I'm receiving an error:

Starting nginx: nginx: [emerg] unknown "ip.0" variable

When trying to start nginx on a new server.

**Comment by Umkus** [comment]
Hello.
What version of nginx do you have?
This is not via the provided docker-compose, right?

**Comment by ulic75** [comment]
Looks like it's version 1.10.3.  Yes correct.  I'm just trying to use the config files, without docker.

**Comment by Umkus** [comment]
That should do it.

**Comment by ulic75** [comment]
Indeed it did.  Thanks!
